version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.16.13
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              ACCOUNT_ID='522523405805'
              REGION='us-east-1'
              CLUSTER='SUPEREZ-APPLICATION-CLUSTER1'
              FAMILY='superez-admin-task-definition'
              DOCKER_IMAGE='superez-admin'
              TASK='superez-admin-task-definition'
              CONTAINER='superez-admin'
              SERVICE='superez-admin-service'

              # Login to AWS
              aws configure set region $REGION
              $(aws ecr get-login --no-include-email --region $REGION)

              # Tag and push docker image
              docker tag app $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1

              # Create task for docker deploy
              task_template='[
                {
                    "logConfiguration": {
                        "logDriver": "awslogs",
                        "options": {
                            "awslogs-group": "/ecs/superez-admin-task-definition",
                            "awslogs-region": "us-east-1",
                            "awslogs-stream-prefix": "ecs"
                        }
                    },
                    "portMappings": [
                        {
                            "hostPort": 0,
                            "protocol": "tcp",
                            "containerPort": 3000
                        }
                    ],
                    "cpu": 0,
                    "environment": [],
                    "mountPoints": [],
                    "memoryReservation": 128,
                    "volumesFrom": [],
                    "name": "%s",
                    "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                    "essential": true
                }
              ]'
              echo "$task_template"

              task_def=$(printf "$task_template" $CONTAINER $ACCOUNT_ID $REGION $DOCKER_IMAGE $CIRCLE_SHA1)

              # Register task definition
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")

              # Grab revision # using regular bash and grep
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')

              # Deploy revision
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi
